version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
