services:
   management-center:
      image: "quay.io/hazelcast_cloud/management-center-flow:latest"
      pull_policy: "always"
      ports:
         - "8080:8080"
      healthcheck:
         test: curl --fail http://localhost:8080/health || exit 1
         interval: 30s
         timeout: 5s
         retries: 3
      environment:
         - JAVA_OPTS=-Dhazelcast.mc.flow.address=http://localhost:9021 -Dhazelcast.mc.flow.internalAddress=http://hazelcast-flow:9021
         - MC_LICENSE=${MC_LICENSE}
         - MC_DEFAULT_CLUSTER=orbital
         - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast-flow:25701
         - MC_APPLICATION_CLIENT_SECRET=changemechangemechangeme
         - MC_INIT_CMD=./bin/mc-conf.sh security reset && ./bin/mc-conf.sh user create -n admin -r admin -p "Password1!"

   hazelcast-flow:
      image: "quay.io/hazelcast_cloud/hazelcast-flow-internal:next"
      restart: unless-stopped
      pull_policy: "always"
      healthcheck:
         test: curl --fail http://localhost:9021/api/actuator/health || exit 1
         interval: 30s
         timeout: 5s
         retries: 3
      environment:
         MC_LICENSE: "${MC_LICENSE}"
         VYNE_SECURITY_OPENIDP_SCOPE: "openid email profile"
         JAVA_OPTS: >-
           -XX:MaxRAMPercentage=50
           -XX:InitialRAMPercentage=50
         OPTIONS: >-
           --flow.analytics.persistRemoteCallResponses=true
           --flow.analytics.persistResults=true
           --flow.db.database=flow
           --flow.db.username=flow
           --flow.db.password=changeme
           --flow.db.host=pg-pagila
           --flow.workspace.config-file=/opt/service/workspace/workspace.conf
           --flow.security.openIdp.enabled=true
           --flow.security.openIdp.jwks-uri=http://management-center:8080/oauth2/jwks
           --flow.security.openIdp.issuerUrl=http://localhost:8080
           --flow.security.openIdp.clientId=flow-client
           --flow.security.openIdp.require-https=false
           --flow.security.open-idp.roles.format=path
           --flow.security.open-idp.roles.path=roles
           --flow.security.open-idp.refreshTokensDisabled=true
           --flow.config.custom.managementCenterUrl=http://localhost:8080
      ports:
         - "9021:9021"
      volumes:
          - ~/.hazelcast/flow/license/:/opt/var/flow/license/
          - .:/opt/service/workspace
      depends_on:
          - pg-pagila
      deploy:
         restart_policy:
            condition: on-failure
         resources:
            limits:
               memory: 2gb

   pg-pagila:
      build:
         context: "docker/pagila-database"
         dockerfile: "Dockerfile"
      expose:
         - 5432
      ports:
         - "35432:5432"
      environment:
         POSTGRES_DB: pagila
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: admin

   films-api:
      build:
         context: "."
         dockerfile: "Dockerfile"
      expose:
         - 80
      ports:
         - "9981:80"
      environment:
         OPTIONS: >-
            --spring.kafka.bootstrap-servers=kafka:19092
      deploy:
         restart_policy:
            condition: on-failure
         resources:
            limits:
               memory: 300mb

   kafka:
      image: "docker.io/apache/kafka:3.7.0"
      hostname: kafka
      container_name: kafka
      environment:
         KAFKA_NODE_ID: 1
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
         KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
         KAFKA_PROCESS_ROLES: 'broker,controller'
         KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
         KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://0.0.0.0:19092'
         KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
         KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
         CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
         KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
         KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
         KAFKA_LOG_RETENTION_MS: 60000
         KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ports:
         - "19092:19092"

volumes:
   postgres_data:
